{"name": "No se permite agregar más de un cónyuge", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=138.0.7204.101)\nStacktrace:\n0   chromedriver                        0x0000000104668eb4 cxxbridge1$str$ptr + 2722840\n1   chromedriver                        0x0000000104660dbc cxxbridge1$str$ptr + 2689824\n2   chromedriver                        0x00000001041b23ec cxxbridge1$string$len + 90648\n3   chromedriver                        0x000000010418c144 chromedriver + 131396\n4   chromedriver                        0x000000010422160c cxxbridge1$string$len + 545848\n5   chromedriver                        0x000000010423a454 cxxbridge1$string$len + 647808\n6   chromedriver                        0x00000001041ed834 cxxbridge1$string$len + 333408\n7   chromedriver                        0x000000010462bfd0 cxxbridge1$str$ptr + 2473268\n8   chromedriver                        0x000000010462f23c cxxbridge1$str$ptr + 2486176\n9   chromedriver                        0x000000010460da18 cxxbridge1$str$ptr + 2348924\n10  chromedriver                        0x000000010462faf8 cxxbridge1$str$ptr + 2488412\n11  chromedriver                        0x00000001045feaa8 cxxbridge1$str$ptr + 2287628\n12  chromedriver                        0x000000010464f9e8 cxxbridge1$str$ptr + 2619212\n13  chromedriver                        0x000000010464fb74 cxxbridge1$str$ptr + 2619608\n14  chromedriver                        0x00000001046609f8 cxxbridge1$str$ptr + 2688860\n15  libsystem_pthread.dylib             0x0000000188369f94 _pthread_start + 136\n16  libsystem_pthread.dylib             0x0000000188364d34 thread_start + 8\n\n", "trace": "  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/common_steps.py\", line 11, in step_impl\n    context.driver.get(context.base_url)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 355, in get\n    self.execute(Command.GET, {\"url\": url})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given que el usuario accede al formulario de Queplan", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=138.0.7204.101)\nStacktrace:\n0   chromedriver                        0x0000000104668eb4 cxxbridge1$str$ptr + 2722840\n1   chromedriver                        0x0000000104660dbc cxxbridge1$str$ptr + 2689824\n2   chromedriver                        0x00000001041b23ec cxxbridge1$string$len + 90648\n3   chromedriver                        0x000000010418c144 chromedriver + 131396\n4   chromedriver                        0x000000010422160c cxxbridge1$string$len + 545848\n5   chromedriver                        0x000000010423a454 cxxbridge1$string$len + 647808\n6   chromedriver                        0x00000001041ed834 cxxbridge1$string$len + 333408\n7   chromedriver                        0x000000010462bfd0 cxxbridge1$str$ptr + 2473268\n8   chromedriver                        0x000000010462f23c cxxbridge1$str$ptr + 2486176\n9   chromedriver                        0x000000010460da18 cxxbridge1$str$ptr + 2348924\n10  chromedriver                        0x000000010462faf8 cxxbridge1$str$ptr + 2488412\n11  chromedriver                        0x00000001045feaa8 cxxbridge1$str$ptr + 2287628\n12  chromedriver                        0x000000010464f9e8 cxxbridge1$str$ptr + 2619212\n13  chromedriver                        0x000000010464fb74 cxxbridge1$str$ptr + 2619608\n14  chromedriver                        0x00000001046609f8 cxxbridge1$str$ptr + 2688860\n15  libsystem_pthread.dylib             0x0000000188369f94 _pthread_start + 136\n16  libsystem_pthread.dylib             0x0000000188364d34 thread_start + 8\n\n", "trace": "  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/common_steps.py\", line 11, in step_impl\n    context.driver.get(context.base_url)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 355, in get\n    self.execute(Command.GET, {\"url\": url})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1752524591467, "stop": 1752524591469}, {"name": "When ingresa datos de contratante con rut \"17470576-3\"", "status": "skipped", "start": 1752524591537, "stop": 1752524591537}, {"name": "And ingresa datos de beneficiario con rut \"15046896-5\"", "status": "skipped", "start": 1752524591537, "stop": 1752524591537}, {"name": "And agrega otro cónyuge con rut \"6065750-5\"", "status": "skipped", "start": 1752524591537, "stop": 1752524591537}, {"name": "And hace clic en Siguiente paso", "status": "skipped", "start": 1752524591537, "stop": 1752524591537}, {"name": "Then debe mostrarse el mensaje de error \"Hay más de un perfil con la relación Conyugé. Solo puede haber uno.\"", "status": "skipped", "start": 1752524591537, "stop": 1752524591537}], "start": 1752524588896, "stop": 1752524591537, "uuid": "16203661-b354-4909-b8bf-5eaa9860cf97", "historyId": "2acead2e5bc23ff9b4d5c8548b012223", "fullName": "Flujo completo de contratación de seguro en Queplan: No se permite agregar más de un cónyuge", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "queplan"}, {"name": "tag", "value": "regression"}, {"name": "feature", "value": "Flujo completo de contratación de seguro en Queplan"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}